### ISSUE TITLE
npm warn EBADENGINE Unsupported engine

### ISSUE THREAD

**Issue by sporteka2** [jedluk/maplibre-compass-pro#8]
$ npm i maplibre-compass-pro
npm warn EBADENGINE Unsupported engine {
npm warn EBADENGINE   package: 'maplibre-compass-pro@0.5.0',
npm warn EBADENGINE   required: { node: '20', npm: '10' },
npm warn EBADENGINE   current: { node: 'v22.4.1', npm: '10.8.1' }
npm warn EBADENGINE }

Hello! How do I fix it?

**Comment by jedluk** [comment]
Hi there! Actually nothing to fix on your end. Package has strict engine mode enabled. The warning says that your setup (node v22.4.1) is incompatible with version defined in package.json. I changed the rules to allow node in versions >=20.
 v0.6.0 is already released
Please try to reinstall 😊
